### ISSUE TITLE
Fill out the Animals and Vegetations.

### ISSUE THREAD

**Issue by ShawnClake** [ShawnClake/374Animals#1]
Override the class properties for each animal and vegetation. Use the generate method to have additional logic for doing so rather than using flat values.

**Comment by ShawnClake** [comment]
Make sure to use **your branch** to push commits

**Comment by ShawnClake** [comment]
With regards to eats level, there's two fields to this. There is also a predator vs prey variable which you haven't set on any of the Animals yet.

Think of it like this, you must design a food chain. First, designate each animal as **either** _predator_ or _prey_ using the eats variable. Then, for all of the prey animals, each one be given a **unique** _eatsLevel_. Thus, you are defining a food chain amoungst the prey animals. The same thing must be done for each predator animal.

The simulation is not saying a predator can not eat a predator. It is also not saying a prey cannot eat a prey. It is, however, splitting our given animal kingdom in half: those animals which are most likely to be prey, and those most likely to be a predator. 

It would be far too complex to try to design an exact animal food chain. When this is all said and done, a predator is **guaranteed** to eat a prey in all circumstances. If two animals are the same _eats_ type (Ie: two animals marked as prey) then the _eatsLevel_ is used to break the tie, with the higher _eatsLevel_ winning the battle.

**Comment by ShawnClake** [comment]
The hunger variables on each animal actually represents **_how full the animal is_**. **_0 means the animal is starved and its max value means it is famished._** The naming of variable is atrocious (my bad!), but please use this convention for all of the animals. Please ensure you set hunger equal to the animals maxHunger for each animal.

**Comment by Uyser** [comment]
Umm, starved and famished mean the same thing. That didn't help at all!!!

**Comment by Uyser** [comment]
Oh nvm, I get it now

**Comment by ShawnClake** [comment]
Yea, my bad. I meant to say 0 means the animal is starved and its max value means its full. :P
