### ISSUE TITLE
Fix UI as well Incorporate Changes

### ISSUE THREAD

**Issue by herasymj** [ShawnClake/374Animals#13]
- Fix enter instruction and tell user to enter x and y coordinates
- Incorporate way to run til end
- Adding randomly or entering values for the numbers of animals

**Comment by herasymj** [comment]
- Document

**Comment by herasymj** [comment]
Fixed the instructions and enter x and y coordinates.
- Sam and Uys are dealing with getting the other two components to work
Still need to finish the document

**Comment by SamPhil** [comment]
Sam is finished the UI for his changes
