### ISSUE TITLE
Fill out the ui.java class and the menu.java class

### ISSUE THREAD

**Issue by ShawnClake** [ShawnClake/374Animals#2]
Fill in each method and ensure we have the ability to print out events, days remaining, and a menu.

NOTE: A method to print out the world will also need to be created using only the tile array data which would be passed in from the World class.

NOTE 2: A method to print out a single tile. Provide more detail about the animal/vegetation that exists on this tile than what the above printWorld method would do. IE. Include names/descriptions/hunger/healths etc.

**Comment by ShawnClake** [comment]
Just a heads up - make sure when you're done your feature branch you: 
1. Pull the changes that the rest of us have made to master into your branch.
2. Handle merge conflicts in your branch
3. Once any merge conflicts have been sorted out push your branch and merge to master.

_If you're worried about breaking your own code when you're fixing merge conflicts, make a backup first._

**Comment by herasymj** [comment]
Done :)
